
#ifndef TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT_H
#define TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT_H

#ifdef TURKBANKSSTREAMLINEFILTERSOURCES_STATIC_DEFINE
#  define TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT
#  define TURKBANKSSTREAMLINEFILTERSOURCES_NO_EXPORT
#else
#  ifndef TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT
#    ifdef TurkBanksStreamlineFilterSources_EXPORTS
        /* We are building this library */
#      define TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef TURKBANKSSTREAMLINEFILTERSOURCES_NO_EXPORT
#    define TURKBANKSSTREAMLINEFILTERSOURCES_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED
#  define TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED_EXPORT
#  define TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED_EXPORT TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED
#endif

#ifndef TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED_NO_EXPORT
#  define TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED_NO_EXPORT TURKBANKSSTREAMLINEFILTERSOURCES_NO_EXPORT TURKBANKSSTREAMLINEFILTERSOURCES_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TURKBANKSSTREAMLINEFILTERSOURCES_NO_DEPRECATED
#    define TURKBANKSSTREAMLINEFILTERSOURCES_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: TurkBanksStreamlineFilterSourcesModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* TURKBANKSSTREAMLINEFILTERSOURCES_EXPORT_H */
